apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>GitOps Homepage</title>
      </head>
      <body>
        <h1>Hello from GitOps New update</h1>
      </body>
    </html>

